-- Matches table for mutual like detection
create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  user1_id uuid not null references auth.users(id) on delete cascade,
  user2_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint matches_no_self_match check (user1_id <> user2_id)
);

create unique index if not exists matches_unique_pair_idx
  on public.matches (user1_id, user2_id);

alter table public.matches enable row level security;

drop policy if exists "matches_select_own_rows" on public.matches;
create policy "matches_select_own_rows"
on public.matches
for select
to authenticated
using (auth.uid() = user1_id or auth.uid() = user2_id);

drop policy if exists "matches_insert_own_rows" on public.matches;
create policy "matches_insert_own_rows"
on public.matches
for insert
to authenticated
with check (auth.uid() = user1_id or auth.uid() = user2_id);

drop policy if exists "matches_update_none" on public.matches;
create policy "matches_update_none"
on public.matches
for update
to authenticated
using (false)
with check (false);

drop policy if exists "matches_delete_none" on public.matches;
create policy "matches_delete_none"
on public.matches
for delete
to authenticated
using (false);

-- Required for mutual-like lookup in the app.
-- If the current swipes policy only allows selecting your own rows,
-- add this policy so the client can read the target user's "like" row
-- and determine whether a mutual like exists.
drop policy if exists "swipes_select_own_or_target_rows" on public.swipes;
create policy "swipes_select_own_or_target_rows"
on public.swipes
for select
to authenticated
using (auth.uid() = user_id or auth.uid() = target_user_id);
